apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  labels:
    app: ecommerce
    component: cart-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: jilspatel/backend-cart-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret
                  key: JWT_SECRET
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: NODE_ENV
