---
- hosts: web
  become: true

  vars:
    backend_image: "{{ backend_repo }}:{{ tag }}"
    frontend_image: "{{ frontend_repo }}:{{ tag }}"

  roles:
    - role: common
      tags: ['common']
    - role: cleanup
      tags: ['cleanup']
    - role: backend
      tags: ['backend']
    - role: frontend
      tags: ['frontend']
