---
- hosts: web
  become: true

  vars:
    backend_image: "{{ backend_repo }}:{{ tag }}"
    frontend_image: "{{ frontend_repo }}:{{ tag }}"

  roles:
    - common
    - cleanup
    - backend
    - frontend
